importation des librairies

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
filepath = "/Users/paulrousseau/Desktop/projet_guigue/regression/forest_fires_doss/forestfires.csv"

data = pd.read_csv(filepath, header = 0)

In [4]:
data.describe(percentiles=None, include=None, exclude=None)

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,4.669246,4.299807,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,12.847292
std,2.313778,1.229900,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,63.655818
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,0.000000
25%,3.000000,4.000000,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,0.000000
50%,4.000000,4.000000,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,0.520000
75%,7.000000,5.000000,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,6.570000
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,1090.840000

In [42]:
from sklearn import svm,linear_model, naive_bayes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [55]:


#les variables "month" et "day" (aussi "X" et "Y" ?), on fait du one hot encoding pour les convertir en variable numériques
#car le svm ne fonctionne que sur des données numériques

# Séparez les colonnes numériques et catégorielles
numerical_cols = data.select_dtypes(include=['int', 'float']).columns
categorical_cols = data.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_cols),  # conserve les colonnes numériques
        ('cat', OneHotEncoder(), categorical_cols)  # applique OneHotEncoder aux colonnes catégorielles
    ])

# Appliquez la transformation
data_encoded = pd.DataFrame(preprocessor.fit_transform(data), columns=list(numerical_cols) + list(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols)))


#on sauvegarde les noms des colonnes dans un dictionnaire, car on va passer en numpy et les array numpy ne conservent pas les noms de colonnes
column_names = data_encoded.columns.tolist()
dico_columns = {variable: indice for indice, variable in enumerate(column_names)}

#passage à un numpy array
data_array = np.array(data_encoded)


X = data_array[:,:-1]
y = data_array[:,-1]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)


mod_SVM1 = svm.SVC(kernel="linear")
mod_SVM2 = svm.SVC(gamma = 2)

mod_SVM1.fit(X_train, y_train)
mod_SVM2.fit(X_train, y_train)

yhat1 = mod_SVM1.predict(X_test)
yhat2 = mod_SVM2.predict(X_test)